using CsvHelper.Configuration;

namespace ESFA.DC.ILR.ReportService.Reports.Funding.DevolvedOccupancy.Model
{
    public class DevolvedAdultEducationOccupancyReportClassMap : ClassMap<DevolvedAdultEducationOccupancyReportModel>
    {
        public DevolvedAdultEducationOccupancyReportClassMap()
        {
            Map(m => m.Learner.LearnRefNumber).Name(@"Learner reference number");
            Map().Name(@"Unique learner number");
            Map().Name(@"Date of birth");
            Map().Name(@"Postcode prior to enrolment");
            Map().Name(@"Pre-merger UKPRN");
            Map().Name(@"Campus identifier");
            Map().Name(@"Provider specified learner monitoring (A)");
            Map().Name(@"Provider specified learner monitoring (B)");
            Map().Name(@"Aim sequence number");
            Map().Name(@"Learning aim reference");
            Map().Name(@"Learning aim title");
            Map().Name(@"Software supplier aim identifier");
            Map().Name(@"Applicable funding rate from ESOL hours");
            Map().Name(@"Applicable funding rate");
            Map().Name(@"Applicable programme weighting");
            Map().Name(@"Aim value");
            Map().Name(@"Notional NVQ level");
            Map().Name(@"Tier 2 sector subject area");
            Map().Name(@"Funding model");
            Map().Name(@"Funding adjustment for prior learning");
            Map().Name(@"Other funding adjustment");
            Map().Name(@"Original learning start date");
            Map().Name(@"Learning start date");
            Map().Name(@"Learning planned end date");
            Map().Name(@"Completion status");
            Map().Name(@"Learning actual end date");
            Map().Name(@"Outcome");
            Map().Name(@"Additional delivery hours");
            Map().Name(@"Learning start date postcode");
            Map().Name(@"Applicable area from source of funding");
            Map().Name(@"Learning delivery funding and monitoring type – source of funding");
            Map().Name(@"Learning delivery funding and monitoring type – full or co funding indicator ");
            Map().Name(@"Learning delivery funding and monitoring type – learning support funding (highest applicable)");
            Map().Name(@"Learning delivery funding and monitoring type - LSF date applies from (earliest)");
            Map().Name(@"Learning delivery funding and monitoring type - LSF date applies to (latest)");
            Map().Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (A)");
            Map().Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (B)");
            Map().Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (C)");
            Map().Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (D)");
            Map().Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (E)");
            Map().Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (F)");
            Map().Name(@"Learning delivery funding and monitoring type - devolved area monitoring (A)");
            Map().Name(@"Learning delivery funding and monitoring type - devolved area monitoring (B)");
            Map().Name(@"Learning delivery funding and monitoring type - devolved area monitoring (C)");
            Map().Name(@"Learning delivery funding and monitoring type - devolved area monitoring (D)");
            Map().Name(@"Learning delivery funding and monitoring type – restart indicator");
            Map().Name(@"Provider specified delivery monitoring (A)");
            Map().Name(@"Provider specified delivery monitoring (B)");
            Map().Name(@"Provider specified delivery monitoring (C)");
            Map().Name(@"Provider specified delivery monitoring (D)");
            Map().Name(@"Funding line type");
            Map().Name(@"Planned number of on programme instalments");
            Map().Name(@"Achievement element (potential or actual earned cash)");
            Map().Name(@"Achievement percentage (aggregated maximum value)");
            Map().Name(@"Non-public-funded contribution");
            Map().Name(@"Capping factor");
            Map().Name(@"Sub contracted or partnership UKPRN");
            Map().Name(@"Delivery location postcode");
            Map().Name(@"Area uplift");
            Map().Name(@"Disadvantage uplift");
            Map().Name(@"Date used for uplifts and other lookups");
            Map().Name(@"August on programme earned cash");
            Map().Name(@"August balancing payment earned cash");
            Map().Name(@"August aim achievement earned cash");
            Map().Name(@"August job outcome earned cash");
            Map().Name(@"August learning support earned cash");
            Map().Name(@"September on programme earned cash");
            Map().Name(@"September balancing payment earned cash");
            Map().Name(@"September aim achievement earned cash");
            Map().Name(@"September job outcome earned cash");
            Map().Name(@"September learning support earned cash");
            Map().Name(@"October on programme earned cash");
            Map().Name(@"October balancing payment earned cash");
            Map().Name(@"October aim achievement earned cash");
            Map().Name(@"October job outcome earned cash");
            Map().Name(@"October learning support earned cash");
            Map().Name(@"November on programme earned cash");
            Map().Name(@"November balancing payment earned cash");
            Map().Name(@"November aim achievement earned cash");
            Map().Name(@"November job outcome earned cash");
            Map().Name(@"November learning support earned cash");
            Map().Name(@"December on programme earned cash");
            Map().Name(@"December balancing payment earned cash");
            Map().Name(@"December aim achievement earned cash");
            Map().Name(@"December job outcome earned cash");
            Map().Name(@"December learning support earned cash");
            Map().Name(@"January on programme earned cash");
            Map().Name(@"January balancing payment earned cash");
            Map().Name(@"January aim achievement earned cash");
            Map().Name(@"January job outcome earned cash");
            Map().Name(@"January learning support earned cash");
            Map().Name(@"February on programme earned cash");
            Map().Name(@"February balancing payment earned cash");
            Map().Name(@"February aim achievement earned cash");
            Map().Name(@"February job outcome earned cash");
            Map().Name(@"February learning support earned cash");
            Map().Name(@"March on programme earned cash");
            Map().Name(@"March balancing payment earned cash");
            Map().Name(@"March aim achievement earned cash");
            Map().Name(@"March job outcome earned cash");
            Map().Name(@"March learning support earned cash");
            Map().Name(@"April on programme earned cash");
            Map().Name(@"April balancing payment earned cash");
            Map().Name(@"April aim achievement earned cash");
            Map().Name(@"April job outcome earned cash");
            Map().Name(@"April learning support earned cash");
            Map().Name(@"May on programme earned cash");
            Map().Name(@"May balancing payment earned cash");
            Map().Name(@"May aim achievement earned cash");
            Map().Name(@"May job outcome earned cash");
            Map().Name(@"May learning support earned cash");
            Map().Name(@"June on programme earned cash");
            Map().Name(@"June balancing payment earned cash");
            Map().Name(@"June aim achievement earned cash");
            Map().Name(@"June job outcome earned cash");
            Map().Name(@"June learning support earned cash");
            Map().Name(@"July on programme earned cash");
            Map().Name(@"July balancing payment earned cash");
            Map().Name(@"July aim achievement earned cash");
            Map().Name(@"July job outcome earned cash");
            Map().Name(@"July learning support earned cash");
            Map().Name(@"Total on programme earned cash");
            Map().Name(@"Total balancing payment earned cash");
            Map().Name(@"Total aim achievement earned cash");
            Map().Name(@"Total job outcome earned cash");
            Map().Name(@"Total learning support earned cash");
            Map().Name(@"Total earned cash");
            Map().Name(@"OFFICIAL – SENSITIVE").Constant(@"OFFICIAL – SENSITIVE");
        }
    }
}
