using System;
using System.Collections.Generic;
using System.Text;
using CsvHelper.Configuration;

namespace ESFA.DC.ILR.ReportService.Reports.Funding.DevolvedOccupancy.Model
{
    public class DevolvedAdultEducationOccupancyReportClassMap : ClassMap<DevolvedAdultEducationOccupancyReportModel>
    {
        public DevolvedAdultEducationOccupancyReportClassMap()
        {
            Map(m => "").Name(@"Learner reference number");
            Map(m => "").Name(@"Unique learner number");
            Map(m => "").Name(@"Date of birth");
            Map(m => "").Name(@"Postcode prior to enrolment");
            Map(m => "").Name(@"Pre-merger UKPRN");
            Map(m => "").Name(@"Campus identifier");
            Map(m => "").Name(@"Provider specified learner monitoring (A)");
            Map(m => "").Name(@"Provider specified learner monitoring (B)");
            Map(m => "").Name(@"Aim sequence number");
            Map(m => "").Name(@"Learning aim reference");
            Map(m => "").Name(@"Learning aim title");
            Map(m => "").Name(@"Software supplier aim identifier");
            Map(m => "").Name(@"Applicable funding rate from ESOL hours");
            Map(m => "").Name(@"Applicable funding rate");
            Map(m => "").Name(@"Applicable programme weighting");
            Map(m => "").Name(@"Aim value");
            Map(m => "").Name(@"Notional NVQ level");
            Map(m => "").Name(@"Tier 2 sector subject area");
            Map(m => "").Name(@"Funding model");
            Map(m => "").Name(@"Funding adjustment for prior learning");
            Map(m => "").Name(@"Other funding adjustment");
            Map(m => "").Name(@"Original learning start date");
            Map(m => "").Name(@"Learning start date");
            Map(m => "").Name(@"Learning planned end date");
            Map(m => "").Name(@"Completion status");
            Map(m => "").Name(@"Learning actual end date");
            Map(m => "").Name(@"Outcome");
            Map(m => "").Name(@"Additional delivery hours");
            Map(m => "").Name(@"Learning start date postcode");
            Map(m => "").Name(@"Applicable area from source of funding");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – source of funding");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – full or co funding indicator ");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning support funding (highest applicable)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type - LSF date applies from (earliest)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type - LSF date applies to (latest)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (A)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (B)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (C)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (D)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (E)  ");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – learning delivery monitoring (F)  ");
            Map(m => "").Name(@"Learning delivery funding and monitoring type - devolved area monitoring (A)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type - devolved area monitoring (B)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type - devolved area monitoring (C)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type - devolved area monitoring (D)");
            Map(m => "").Name(@"Learning delivery funding and monitoring type – restart indicator  ");
            Map(m => "").Name(@"Provider specified delivery monitoring (A)");
            Map(m => "").Name(@"Provider specified delivery monitoring (B)");
            Map(m => "").Name(@"Provider specified delivery monitoring (C)");
            Map(m => "").Name(@"Provider specified delivery monitoring (D)");
            Map(m => "").Name(@"Funding line type");
            Map(m => "").Name(@"Planned number of on programme instalments");
            Map(m => "").Name(@"Achievement element (potential or actual earned cash)");
            Map(m => "").Name(@"Achievement percentage (aggregated maximum value)");
            Map(m => "").Name(@"Non-public-funded contribution");
            Map(m => "").Name(@"Capping factor");
            Map(m => "").Name(@"Sub contracted or partnership UKPRN");
            Map(m => "").Name(@"Delivery location postcode");
            Map(m => "").Name(@"Area uplift");
            Map(m => "").Name(@"Disadvantage uplift");
            Map(m => "").Name(@"Date used for uplifts and other lookups");
            Map(m => "").Name(@"August on programme earned cash");
            Map(m => "").Name(@"August balancing payment earned cash");
            Map(m => "").Name(@"August aim achievement earned cash");
            Map(m => "").Name(@"August job outcome earned cash");
            Map(m => "").Name(@"August learning support earned cash");
            Map(m => "").Name(@"September on programme earned cash");
            Map(m => "").Name(@"September balancing payment earned cash");
            Map(m => "").Name(@"September aim achievement earned cash");
            Map(m => "").Name(@"September job outcome earned cash");
            Map(m => "").Name(@"September learning support earned cash");
            Map(m => "").Name(@"October on programme earned cash");
            Map(m => "").Name(@"October balancing payment earned cash");
            Map(m => "").Name(@"October aim achievement earned cash");
            Map(m => "").Name(@"October job outcome earned cash");
            Map(m => "").Name(@"October learning support earned cash");
            Map(m => "").Name(@"November on programme earned cash");
            Map(m => "").Name(@"November balancing payment earned cash");
            Map(m => "").Name(@"November aim achievement earned cash");
            Map(m => "").Name(@"November job outcome earned cash");
            Map(m => "").Name(@"November learning support earned cash");
            Map(m => "").Name(@"December on programme earned cash");
            Map(m => "").Name(@"December balancing payment earned cash");
            Map(m => "").Name(@"December aim achievement earned cash");
            Map(m => "").Name(@"December job outcome earned cash");
            Map(m => "").Name(@"December learning support earned cash");
            Map(m => "").Name(@"January on programme earned cash");
            Map(m => "").Name(@"January balancing payment earned cash");
            Map(m => "").Name(@"January aim achievement earned cash");
            Map(m => "").Name(@"January job outcome earned cash");
            Map(m => "").Name(@"January learning support earned cash");
            Map(m => "").Name(@"February on programme earned cash");
            Map(m => "").Name(@"February balancing payment earned cash");
            Map(m => "").Name(@"February aim achievement earned cash");
            Map(m => "").Name(@"February job outcome earned cash");
            Map(m => "").Name(@"February learning support earned cash");
            Map(m => "").Name(@"March on programme earned cash");
            Map(m => "").Name(@"March balancing payment earned cash");
            Map(m => "").Name(@"March aim achievement earned cash");
            Map(m => "").Name(@"March job outcome earned cash");
            Map(m => "").Name(@"March learning support earned cash");
            Map(m => "").Name(@"April on programme earned cash");
            Map(m => "").Name(@"April balancing payment earned cash");
            Map(m => "").Name(@"April aim achievement earned cash");
            Map(m => "").Name(@"April job outcome earned cash");
            Map(m => "").Name(@"April learning support earned cash");
            Map(m => "").Name(@"May on programme earned cash");
            Map(m => "").Name(@"May balancing payment earned cash");
            Map(m => "").Name(@"May aim achievement earned cash");
            Map(m => "").Name(@"May job outcome earned cash");
            Map(m => "").Name(@"May learning support earned cash");
            Map(m => "").Name(@"June on programme earned cash");
            Map(m => "").Name(@"June balancing payment earned cash");
            Map(m => "").Name(@"June aim achievement earned cash");
            Map(m => "").Name(@"June job outcome earned cash");
            Map(m => "").Name(@"June learning support earned cash");
            Map(m => "").Name(@"July on programme earned cash");
            Map(m => "").Name(@"July balancing payment earned cash");
            Map(m => "").Name(@"July aim achievement earned cash");
            Map(m => "").Name(@"July job outcome earned cash");
            Map(m => "").Name(@"July learning support earned cash");
            Map(m => "").Name(@"Total on programme earned cash");
            Map(m => "").Name(@"Total balancing payment earned cash");
            Map(m => "").Name(@"Total aim achievement earned cash");
            Map(m => "").Name(@"Total job outcome earned cash");
            Map(m => "").Name(@"Total learning support earned cash");
            Map(m => "").Name(@"Total earned cash");
            Map(m => "").Name(@"OFFICIAL – SENSITIVE");
        }
    }
}
